-- DESIGNING OF AIRBNB TYPE PLATFORMS
-- DESIGNING OF  DB SCHEMA FOR A VACATION RENTAL PLATFORM
-- HOUSES--LISTING, --GUEST -- USER ,, HOST --OWNER OF PLATFORM
                       -- ----------------- DESIGNINGS ---------------

-- LISTINGS 

-- USER --  

-- BOOKINGS (TRACKING ASSOCIATION)

-- PAYMENT Details

-- REVIEWS AND RATING

-- MESSAGINGS 

-- 
 